### PR TITLE
Nano faq

### PR DESCRIPTION
**Pull request by mmontori1**
tried to match it like in design, had to make a separate ExpandedItem just for nano to do that. for some reason, travis ci build fails (idk why?)

### CODE REVIEW

**Comment by connorkrupp** [comment]
Did you run `npm run test`? That should take care of the travis errors, I don't know if I can take the copy/paste of the other ExpandingItem :( 

Also, is this the content Nevin wrote? Some of these faq items don't make sense for Nano

**Comment by connorkrupp** [comment]
Yeah your API for the expanding item is good, maybe change the blackout page's one with yours and pass in the colors for blackout like you are doing here

**Comment by mmontori1** [comment]
so I changed the faq text to the stuff nevin wrote. what should I do about the expandingitem? This is the difference in how they look. (first one is expandingitemnano, second is the original). I could just switch back to the second one and pick colors for the plus, header, and text for the faq items. 
screen shot 2017-06-10 at 2 33 33 pm
screen shot 2017-06-10 at 2 35 07 pm

**Comment by connorkrupp** [comment]
First one definitely looks good, I just don't like how ExpandingItem and ExpandingItemNano are basically the same besides colors. Is there any way you could have the blackout page use your implementation for ExpandingItem and maintain how it looks?

**Comment by mmontori1** [comment]
got it. this is how the changes look on the blackout page
screen shot 2017-06-10 at 2 44 28 pm

**Comment by mmontori1** [comment]
so you want it to look like it does now live (like below)? i could see if i could make it work.
screen shot 2017-06-10 at 2 49 06 pm

**Comment by mmontori1** [comment]
alright i think i got it working all within one ExpandedItem component. Just had to make an additional bool prop called expandColor which decides whether you want it to change colors when expanding. The only problem I can see is that right now, the blackout page + isn't matching exactly along the header for the faq items. This is how it looks now:
screen shot 2017-06-10 at 3 18 42 pm
screen shot 2017-06-10 at 3 18 54 pm

**Comment by mmontori1** [comment]
fixed the plus alignment
screen shot 2017-06-10 at 3 30 20 pm
screen shot 2017-06-10 at 3 30 44 pm

**Pull request merged**
