### PR TITLE
simple footer changes

### PR DESCRIPTION
**Pull request by mmontori1**
changed the footer to match the one on design for nano. all I had to do was remove the header logo flexer, and add a flexer after the image buttons for fb, twitter, etc. Seems to work fine this way

### CODE REVIEW

**Comment by mmontori1** [comment]
screen shot 2017-06-09 at 10 18 39 pm
screen shot 2017-06-09 at 10 24 07 pm

this is how it looks on the current site

**Comment by connorkrupp** [comment]
lol uhhh can you put this on the nano homepage instead of the blackout page

**Comment by mmontori1** [comment]
screen shot 2017-06-09 at 10 42 16 pm
screen shot 2017-06-09 at 10 42 24 pm


lmao didnt realize that the home page was there, since it always would directly send me to the blackout page

**Comment by mmontori1** [comment]
though it currently is outside of the scroll

**Pull request merged**
