### PR TITLE
Added mailto links to the emails in the FAQ

### PR DESCRIPTION
**Pull request by cyanliu**
yay???

### CODE REVIEW

**Comment by connorkrupp** [comment]
Lol thanks for this @cyanliu can you run `npm run test` to fix the CI build

**Comment by cyanliu** [comment]
I was hoping I didn't have to actually configure a local dev environment (I've just been super lazy and edited code right here on GitHub) :[ but yeah I'll get on that today

**Comment by cyanliu** [comment]
@connorkrupp 

Done and done.

**Comment by connorkrupp** [comment]
I love how your commit history shows your emotions

**Comment by cyanliu** [comment]
honestly, commit messages are basically like poetry

**Pull request merged**
