### PR TITLE
fix spaces around links on FAQ page

### PR DESCRIPTION
**Pull request by cooltoast**
### PR Description
Adds jsx spacing around links on the FAQs

### What needs to be reviewed?
That there is a space between words and links within the same sentence.

### Context?
N/A

### CODE REVIEW

**Comment by cooltoast** [comment]
Ok, ran it. What's the next step?

**Comment by cooltoast** [comment]
Am I supposed to run it in Travis?

**Comment by cooltoast** [comment]
Ok I'm not sure why it keeps failing

**Comment by cooltoast** [comment]
am i doing something wrong here

**Comment by antoniomika** [comment]
Our project uses [prettier](https://github.com/prettier/prettier) for handling code cleanup/managing syntax. In order to abide by our coding standards, it's important to pull the repository, `yarn install` the necessary packages, and run `yarn test` to ensure all tests/code standards pass.

**Comment by cooltoast** [comment]
I ran `npm run test` and `yarn test` locally, is that correct? I'm trying to figure out why the Travis builds are failing

**Comment by antoniomika** [comment]
Yes, this is correct. If you check [here](https://travis-ci.org/mhacks/mhacks-web/builds/269430369#L473), you'll see that the prettier command has not properly run. When you run `yarn test` locally, it'll prompt you with a `y/n` as to whether or not correct the style issues found in the code.

**Comment by cooltoast** [comment]
awesome! my bad, thanks for the help

**Pull request merged**
